net-proxy/daed: auth-mount bpf in init.d and fix logger
Signed-off-by: xz-dev <xiangzhedev@gmail.com>

diff --git a/net-proxy/daed/files/daed.initd b/net-proxy/daed/files/daed.initd
--- a/net-proxy/daed/files/daed.initd
+++ b/net-proxy/daed/files/daed.initd
@@ -19,10 +19,21 @@ depend() {
     use net
 }
 
+error() {
+    echo "ERROR: $@" >&2
+    logger "ERROR: $@"
+}
+
 start_pre() {
-    if [ -d /sys/fs/bpf ] && ! mountinfo -q /sys/fs/bpf; then
-        error "bpf filesystem not mounted, exiting..."
-        return 1
+    if [ -d /sys/fs/bpf ]; then
+        if ! mountinfo -q /sys/fs/bpf; then
+            # From: https://github.com/cilium/cilium/blob/main/contrib/systemd/sys-fs-bpf.mount
+            # TODO: looking for sys-fs-bpf.mount in init.d
+            mount -t bpf bpffs /sys/fs/bpf || {
+                error "failed to mount bpf filesystem, exiting..."
+                return 1
+            }
+        fi
     fi
     if [ -d /sys/fs/cgroup ] && ! mountinfo -q /sys/fs/cgroup/; then
         error "cgroup filesystem not mounted, exiting..."
